from schemas.estoque import RespostaEstoqueSchema
from schemas.solicitacao import CriacaoSolicitacaoSchema, SolicitacaoUpdateStatusSchema, RespostaSolicitacaoSchema
from schemas.cadastro import CriacaoCadastroSchema, RespostaCadastroSchema
from schemas.error import ErrorSchema
from schemas.path import IdPathSchema